### PR TITLE
Initial localization support

### PR DESCRIPTION
**Pull request by Pro-pra**
Have nice day!
I tried to add localization using libintl-perl

.pot file generated, on some string i have errors ex.:  ../scriptor:47: invalid variable interpolation at "$"

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
How do you generate the `.pot` file?
How to you generate the `.po` file(s)?
How to you generate the `.mo` file(s)?

Up to now I used a generated Makefile to call the correct "magic" commands.

**Comment by LudovicRousseau** [comment]
@Pro-pra I got no answer fro you.
I am OK to add internationalisation and localosation. But I need your help.

**Comment by Pro-pra** [comment]
Hi, 
sorry, i forgot add Makefile to po dir
it`s based on example from https://github.com/gflohr/libintl-perl/blob/master/sample/simplecal/po/Makefile

i will add this file later.

**Comment by LudovicRousseau** [comment]
Thanks for the Makefile.
I am now able to get a French l10n of scriptor. Nice.

I get the same problem as you for Russian. It looks like the UTFè8 encoding has an issue.
You can test using the branch `i18n` from https://github.com/LudovicRousseau/pcsc-tools-debug/tree/i18n

**Comment by LudovicRousseau** [comment]
I also note that I have no problem with `scriptor` (command line in the console) in French or Russian.
But I can't correctly display French accents in gscriptor. Maybe it is a problem between Perl and Gtk+.

**Comment by Pro-pra** [comment]
I change https://github.com/LudovicRousseau/pcsc-tools-debug/blob/0122025c2485435ff7fc8e12faccf8303b91569b/po/Makefile#L4 to libdir = ../

**Comment by Pro-pra** [comment]
Add
`use utf8; `
not help me for enable utf8 support, need check docs for perl-gtk3 may be

**Comment by LudovicRousseau** [comment]
I tried adding accented letters in https://github.com/LudovicRousseau/pcsc-tools/blob/master/gscriptor#L183 and I have the problem (even without your modifications).

I need to add:
```
 use utf8; 
```
This is expected since, in this case, the script contains utf8 characters so I must indicate it to Perl.

But if I use the `__()` construction the text is wrong again in the Gtk interface. Even for the original English version.

If I use `print(__("_File") . "\n");` I get the correct text (including accents) in the console. So the function `__()` works as expected.

Not idea what the problem is.

**Comment by Pro-pra** [comment]
hmmm.... libintl unicode support need check....
may be [https://github.com/gflohr/libintl-perl/](https://github.com/gflohr/libintl-perl) this project have ansver for this&

**Comment by LudovicRousseau** [comment]
I am not sure the problem is with libintl-perl.
I used this patch:
```diff
diff --git a/gscriptor b/gscriptor
index b4a9db5..46a107f 100755
--- a/gscriptor
+++ b/gscriptor
@@ -205,6 +205,7 @@ sub arrange_widgets () {
         [ "About",             undef,           __("_About"),         "<control>A",        __("About"),                            \&About ],
     );
 
+	print __("_File") . "\n";
     my $ui = Gtk3::UIManager->new();
     my $action_group = Gtk3::ActionGroup->new('AppWindowActions');
     $action_group->add_actions( \@appActions, undef );
diff --git a/po/fr.po b/po/fr.po
index 2c2ca28..52ca83b 100644
--- a/po/fr.po
+++ b/po/fr.po
@@ -18,7 +18,7 @@ msgstr ""
 
 #: ../gscriptor:188
 msgid "_File"
-msgstr ""
+msgstr "Fichier àç"
 
 #: ../gscriptor:189
 msgid "_New"
``` 

And I correctly get the output `Fichier àç`  in the console.
So the function `__()` works as expected.

With `LANG=ru_RU.UTF-8` I get i the console `_Файл`.

**Comment by Pro-pra** [comment]
work in console
not work in gtk3 window
hmmm....

**Comment by Pro-pra** [comment]
Please check this info 
https://metacpan.org/dist/libintl-perl/view/lib/Locale/libintlFAQ.pod#Why-do-non-ASCII-characters-in-my-Gtk2-application-look-messed-up

**Comment by LudovicRousseau** [comment]
It works now.
I updated my i18n branch at https://github.com/LudovicRousseau/pcsc-tools-debug/commits/i18n

The next step: how/where to install the `.mo` files so that perl can find them automatically?

**Comment by Pro-pra** [comment]
Cool!!!

XDG standard path: ex. /usr/share/locale/ru/LC_MESSAGES/pcsc-tools.mo

may be "make install" from ./po directory install all locales to right path?

**Comment by LudovicRousseau** [comment]
Not sure about this path.

It looks like Perl is looking for a `LocaleData` directory in these places:

- `/etc/perl/LocaleData`
- `/usr/lib/x86_64-linux-gnu/perl/5.36/LocaleData`
- `/usr/lib/x86_64-linux-gnu/perl5/5.36/LocaleData`
- `/usr/lib/x86_64-linux-gnu/perl-base/LocaleData`
- `/usr/local/lib/site_perl/LocaleData`
- `/usr/local/lib/x86_64-linux-gnu/perl/5.36.0/LocaleData`
- `/usr/local/share/perl/5.36.0/LocaleData`
- `/usr/share/perl/5.36/LocaleData`
- `/usr/share/perl5/LocaleData`

I am not sure which one to use. On my Debian system none of them exist already.

**Comment by Pro-pra** [comment]
i put locale to /usr/share/locale/ru/LC_MESSAGES and its works fine. 

libintl and gettext and msgfmt utils work with /usr/share/locale/*

**Comment by LudovicRousseau** [comment]
I updated https://github.com/LudovicRousseau/pcsc-tools-debug/tree/i18n

Now you can use the classic:
```
./configure
make
sudo make install
```
Please test on your side and tell me if it works (or not) for you.

**Comment by Pro-pra** [comment]
```
$ LANG=C make -f Makefile.intl update-po
cat: /POTFILES: No such file or directory
make pcsc-tools.pot
make[1]: Entering directory '/home/rosa/tmp/pcsc-tools-debug-i18n/po'
make[1]: Nothing to be done for 'pcsc-tools.pot'.
make[1]: Leaving directory '/home/rosa/tmp/pcsc-tools-debug-i18n/po'
cd ; \
        catalogs='ru fr'; \
        for cat in $catalogs; do \
          cat=`basename $cat`; \
          lang=`echo $cat | sed 's/\.po$//'`; \
          mv $lang.po $lang.old.po; \
          echo "$lang:"; \
          if msgmerge $lang.old.po pcsc-tools.pot -o $lang.po; then \
            rm -f $lang.old.po; \
          else \
            echo "msgmerge for $cat failed!"; \
            rm -f $lang.po; \
            mv $lang.old.po $lang.po; \
          fi; \
        done
mv: cannot stat 'ru.po': No such file or directory
ru:
msgmerge: error while opening "ru.old.po" for reading: No such file or directory
msgmerge for ru failed!
mv: cannot stat 'ru.old.po': No such file or directory
mv: cannot stat 'fr.po': No such file or directory
fr:
msgmerge: error while opening "fr.old.po" for reading: No such file or directory
msgmerge for fr failed!
mv: cannot stat 'fr.old.po': No such file or directory
make: *** [Makefile.intl:79: update-po] Error 1
```
$(srcdir) needed

**Comment by Pro-pra** [comment]
may be need more simple way for work with translations? 
i need "make update-po" and not need compile programm for this.

**Comment by LudovicRousseau** [comment]
We can discuss about complexity if you want.

My question was: do you get the Russian translation after the commands:
```
./configure
make
sudo make install
```

**Comment by Pro-pra** [comment]
configure stage fail:
```
DEBUG: checking for sys/time.h... yes
DEBUG: ./configure: line 4766: syntax error near unexpected token `$datarootdir,'
DEBUG: ./configure: line 4766: `AX_RECURSIVE_EVAL($datarootdir, datarootdir_exp)'
DEBUG: error: Bad exit status from /var/tmp/rpm-tmp.rQm5xB (%build)
```

**Comment by Pro-pra** [comment]
Yes, work good. see screenshot: 
Screenshot_20230403_111906

**Comment by Pro-pra** [comment]
also we have icons pack for desktop file:
[icons.tar.gz](https://github.com/LudovicRousseau/pcsc-tools/files/11134201/icons.tar.gz)
and add to desktop file:
Icon=gscriptor

**Comment by Pro-pra** [comment]
GPL, we use this icons from 2019 year.

**Comment by LudovicRousseau** [comment]
Icon added.
I also i18n more strings. Please update the ru.po file.

**Comment by Pro-pra** [comment]
Thank you! 
updated ru.po attached
[ru.po.gz](https://github.com/LudovicRousseau/pcsc-tools/files/11184667/ru.po.gz)

**Comment by Pro-pra** [comment]
I have error:
```
$ gscriptor
String found where operator expected at /usr/bin/gscriptor line 255, near "# The ""
        (Missing semicolon on previous line?)
String found where operator expected at /usr/bin/gscriptor line 255, near "my $txtReader = Gtk3::Label->new (__(""
        (Missing semicolon on previous line?)
```

**Comment by Pro-pra** [comment]
May be you add this localization patch for desktop file? (fr localization also needed)
```
--- pcsc-tools-1.5.4/gscriptor.desktop  2016-03-20 01:36:46.000000000 +0300
+++ pcsc-tools-1.5.4_patched/gscriptor.desktop  2019-11-12 10:28:22.470791937 +0300
@@ -1,7 +1,9 @@
 [Desktop Entry]
 Name=Gscriptor
 Comment=Send commands to smart cards
+Comment[ru]=Отправка команд на смарт-карты
 Exec=gscriptor
+Icon=gscriptor
 Terminal=false
 Type=Application
 Categories=Utility;GTK;
```

**Comment by LudovicRousseau** [comment]
`gscriptor` problem fixed. Sorry.

I also added l10n for the `.desktop` file.
Where can I see the Comment field displayed?

**Comment by LudovicRousseau** [comment]
> if icons now in /usr/share/icons need set Icons=pcsc-tools in pcsc-tools.desktop.in

There is no ` pcsc-tools.desktop.in` file.
`Icon=` is already in https://github.com/LudovicRousseau/pcsc-tools-debug/blob/i18n/gscriptor.desktop.in#L11

I don't understand what you are talking about here.

Yes, a new release is planned. I am waiting for your "go".

**Comment by LudovicRousseau** [comment]
New i18n strings.
Please provide an updated `ru.po` file.

What do you use gscriptor for? since how long?

**Comment by Pro-pra** [comment]
>why do you use gscriptor?

AltLinux Wirkstation 10.1 have it in-box.

>what do you use your smart card for?

I don't have writable smart cards yet. We just read the currently existing smart cards.

> why not another program?

I don't know about them.

>what do you like in gscriptor?

I'm the maintainer of the Rosa linux distribution, I package a lot of software and help developers make software easy to install.

**Comment by LudovicRousseau** [comment]
I merged the code.
Thanks

The next step is to make a new release of pcsc-tools.

**Pull request closed without merging**
